import Film from "./images/film.jpeg";
const About = () => {
    return (
        <div className="aboutPage">
            <h1 style={{textAlign:"center"}}>Welcome to about page</h1>
            <div className="description">
                <img src={Film} alt="" width="600px" height="550px" />
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit neque aperiam temporibus dicta aliquid veritatis excepturi, eius libero rerum voluptatem dignissimos tenetur similique incidunt reiciendis nisi nihil enim corporis omnis ratione asperiores culpa a totam consequuntur. Officiis ad beatae explicabo tempora earum consequatur cupiditate dolor facere quis distinctio sed numquam, accusamus rerum, itaque odio? Consequuntur, distinctio enim. Dolorem quos labore explicabo nostrum illum, distinctio obcaecati vitae quibusdam. Pariatur ipsa voluptate culpa accusantium assumenda sit aut suscipit odio quae adipisci, dignissimos odit hic iusto error repellat voluptas? Quaerat velit quas dolores perspiciatis rerum sit in repellat qui ratione dignissimos aperiam deleniti suscipit error, dolorum ab laboriosam recusandae doloremque accusantium rem quam obcaecati dolore. Voluptates rem itaque esse, illum vel similique reprehenderit velit unde, repellat beatae voluptas autem eos? Explicabo harum debitis nihil nobis odio asperiores dolorum repellat, laborum illo impedit! Mollitia, eius. Omnis aliquid maiores officia aut quasi aspernatur, dolorum ex et sit ducimus qui reiciendis veritatis labore amet, itaque perferendis natus! Aliquam eius facere officia ipsam error consequuntur voluptatibus enim, voluptatum aut est tenetur et. Id minus doloribus, et, vitae rem vel repellendus laboriosam quis voluptate reprehenderit facilis. Ex beatae laudantium quas dolor ipsa impedit maiores sapiente magni, mollitia laboriosam neque deleniti excepturi? Necessitatibus debitis, alias velit id voluptatem nesciunt quae eveniet? Possimus aliquid at quae assumenda id dolore, excepturi quasi reiciendis laboriosam molestias saepe iusto esse incidunt asperiores inventore iste veritatis quo harum labore eum velit impedit libero dolor? Accusantium eveniet, libero illum odit incidunt nihil nostrum autem dolorum. Distinctio, error eum. Atque, in ipsa quia aut, quidem numquam ullam explicabo odio reiciendis laboriosam doloremque vitae eius nostrum delectus labore? Aperiam autem ullam voluptates laboriosam facere eveniet beatae ab non cumque nulla. Sed quidem expedita voluptas repellat ipsa qui est ratione autem, a nobis iste illo quisquam quae quam ipsam officiis eveniet earum, voluptatum officia modi dolore pariatur sapiente sunt! Tenetur omnis dolorum expedita doloremque facilis molestias natus distinctio non iure reiciendis illum neque in voluptas aliquid optio libero beatae, asperiores voluptates sapiente itaque. Maiores omnis nisi eius, asperiores, architecto qui beatae numquam laborum temporibus quam voluptatibus! Sed, placeat!</p>
            </div>
        </div>
    );
}

export default About;